module.exports = {
  RTT: "Tommy",
  NZL: "Anton",
  PER: "Ben",
  RUM: "Cillian",
  CYP: "Ian",
  SRV: "DanC",
  ALG: "Nick",
  KOJ: "Adam",
  INC: "Kevin",
  GDW: "OliS",
  TRP: "Lawrence",
  MOR: "Callum",
  JAP: "Schrodero",
  BEI: "Ned",
  BTI: "SamF",
  BEN: "pilkman",
  TGT: "OllyN",
  TRE: "Sheb",
  RUS: "Will",
  KAF: "Piaggio",
  SKA: "Josh",
  LXA: "Solon",
  MAY: "Harry",
  TMB: "The Audacity of Cope",
  RAS: "adjb",
  NPL: "SamB",
  MRK: "ybot22",
  OMA: `MintyFresh`,
  MAM: `Pavel`
}